### ISSUE TITLE
Close icon for search

### ISSUE THREAD

**Issue by tim-phillips** [devonashleyberger/contacts#18]
Bootstrap does it like this:

```html
<button type="button" class="close">
  <span aria-hidden="true">&times;</span>
</button>
```

```css
.close {
  float: right;
  font-size: 1.5rem;
  font-weight: 700;
  line-height: 1;
  color: #000;
  text-shadow: 0 1px 0 #fff;
  opacity: .5;
}

.close:hover, .close:focus {
  color: #000;
  text-decoration: none;
  opacity: .75;
}

.close:not(:disabled):not(.disabled) {
  cursor: pointer;
}

button.close {
  padding: 0;
  background-color: transparent;
  border: 0;
  -webkit-appearance: none;
}
```

https://getbootstrap.com/docs/4.0/utilities/close-icon/

https://github.com/twbs/bootstrap/archive/v4.1.0.zip
